### ISSUE TITLE
Automated Channels sync

### ISSUE THREAD

**Issue by AShroti** [hlxsites/caesars-screens#3]
1. Generate base channels.json through Franklin Indexing (https://www.hlx.live/docs/indexing-reference)
2. Automatically generate channels.json (same structure as in AEM https://publish-p43105-e402743.adobeaemcloud.com/screens/channels.json)
3. Link the automation generation with Publish event

**Reference implementation**: https://main--caesars-screens--shrotia.hlx.live/screens/channels.json

**Comment by shrotia** [comment]
Done as part of https://github.com/hlxsites/caesars-screens/pull/13
